### ISSUE TITLE
How to lower the cell sparsity?

### ISSUE THREAD

**Issue by Sophiesze** [bowang-lab/simATAC#1]
Hi, thanks for providing this package. 

I tried to utilize your package on my scATAC-seq data (68 cells). And I choose to use nBins=5000 to balance the library size between the Real and Stimulated groups. However, I notice the sparsity change greatly. I change the augment "sparse.fac" and I did not see any changes? 

Would you mind telling me how to change the cell sparsity?

The plots are attached below.

**nBins=5000, sparse.fac=1**
![image](https://user-images.githubusercontent.com/53801318/119822770-9dadaf00-bf26-11eb-9f17-f1f96b662de5.png)
![image](https://user-images.githubusercontent.com/53801318/119822911-c766d600-bf26-11eb-9002-cb642288ae00.png)
![image](https://user-images.githubusercontent.com/53801318/119822952-cf267a80-bf26-11eb-85fe-aee6c3242e26.png)

**nBins=5000, sparse.fac=0.2**
![image](https://user-images.githubusercontent.com/53801318/119822833-b0c07f00-bf26-11eb-8d7f-88a9367df44a.png)

**If nBins=68,** then the result of cell sparsity seemed better, but the library size varied from the Real and Stimulated group. 
![image](https://user-images.githubusercontent.com/53801318/119823093-ff6e1900-bf26-11eb-90b5-5d2d2e30550f.png)
![image](https://user-images.githubusercontent.com/53801318/119823165-144aac80-bf27-11eb-933d-5c91a711716d.png)
![image](https://user-images.githubusercontent.com/53801318/119823196-1ca2e780-bf27-11eb-8021-a2f0779dcbdf.png)

Thank you so much!

Best regard,
Sophie

**Comment by znavidi** [comment]
Hi Sophie,

Thanks for using our package. 
simATAC learns the distribution of reads across bins and cells based on the number and length of bins given as input, and all the analyses performed in our study are based on bins with the length of 5000 base pairs, as mentioned in the manuscript. This bin length usually leads to the number of bins (nBins parameter) around 600,000 (different for various genome references), which is significantly different from what you set. I do not recommend changing the count and length of bins from the input, as the distribution of reads might change.
 
Also, the sparse.fac parameter only offers users the flexibility to adjust the sparsity in the simulated count matrix as desired. 

I hope this helps. Please let me know if you have any other questions.

Best,
Zeinab
