### ISSUE TITLE
Bin size

### ISSUE THREAD

**Issue by ejc043** [bowang-lab/simATAC#3]
Thank you for the wonderful package! 
The default parameters of simATAC uses 5kb bins. I know there is an ```nBin``` parameter to allow different sized bins. However, I'm unsure how to make 500bp bins. Would you be able to help me?

**Comment by znavidi** [comment]
Hi,
I have not tried it myself, but given that with default setting there are 5000* 642098 base pairs, you could try (5000* 642098)/500 = 6420980 as nBins. Hope this helps!
